# See https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

locale: "en-US"
title: "pf80.ch"
title_separator: "|"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pf80.ch" # the base hostname & protocol for your site, e.g. http://example.com
repository: "pferrot/pferrot.github.io"
name: "Patrice Ferrot"
description: "Patrice Ferrot, freelance consultant for Web / Cloud / Data / Automation."


author:
  name   : "Patrice Ferrot"
  avatar : "/assets/images/patrice.png"
  #bio    : "software engineer<br>&nbsp;&nbsp;&nbsp;&nbsp;backend<br>&nbsp;&nbsp;&nbsp;&nbsp;web services<br>&nbsp;&nbsp;&nbsp;&nbsp;cloud<br>&nbsp;&nbsp;&nbsp;&nbsp;distributed systems<br>&nbsp;&nbsp;&nbsp;&nbsp;devops<br>&nbsp;&nbsp;&nbsp;&nbsp;ci/cd<br>&nbsp;&nbsp;&nbsp;&nbsp;big data<br>(rock) music lover<br>squash player<br>federer fan<br>snowboarder"
  bio    : freelance consultant
  #email  : "top secret :-)"
  #uri    : "https://github.io.pferrot"
  home   : # null (default), "absolute or relative url to link to author home"
  github : "pferrot"
  twitter: "patriceferrot"
  linkedin: "patriceferrot"
  #lastfm: "stupidillusion"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-148509895-1"

twitter:
  username: patriceferrot
# Build settings
markdown: kramdown
#theme: minima
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
#minimal_mistakes_skin: "dirt" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
