# See https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

locale: "en-US"
title: "pf80.ch"
title_separator: "|"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pf80.ch" # the base hostname & protocol for your site, e.g. http://example.com
repository: "pferrot/pferrot.github.io"
name: "pf80.ch"
description: "pf80.ch"


author:
  name   : "pf80"
  avatar : "/assets/images/pf80_winter_square.jpg"
  #bio    : "software engineer<br>&nbsp;&nbsp;&nbsp;&nbsp;backend<br>&nbsp;&nbsp;&nbsp;&nbsp;web services<br>&nbsp;&nbsp;&nbsp;&nbsp;cloud<br>&nbsp;&nbsp;&nbsp;&nbsp;distributed systems<br>&nbsp;&nbsp;&nbsp;&nbsp;devops<br>&nbsp;&nbsp;&nbsp;&nbsp;ci/cd<br>&nbsp;&nbsp;&nbsp;&nbsp;big data<br>(rock) music lover<br>squash player<br>federer fan<br>snowboarder"
  #bio    : freelance consultant
  #email  : "top secret :-)"
  #uri    : "https://github.io.pferrot"
  #home   : # null (default), "absolute or relative url to link to author home"
  github : "pferrot"
  twitter: "patriceferrot"
  #linkedin: "patriceferrot"
  #lastfm: "stupidillusion"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-148509895-1"

twitter:
  username: patriceferrot

# Only used if there is no header image in page.
og_image: "/assets/images/pf80_winter_square_cubism.jpg"

# Build settings
markdown: kramdown
#theme: minima
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages", ".well-known"]

# Not using categories for now at least.
# category_archive:
#   type: liquid
#   path: /categories/

tag_archive:
  type: liquid
  path: /tags/

search: true
# Could affect performance, see https://mmistakes.github.io/minimal-mistakes/docs/configuration/#lunr-default
search_full_content: true
lunr:
  search_within_pages: true

defaults:
  -
    scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      header: false
      #header:
        #image: /assets/images/sf.png
      #  overlay_image: /assets/images/roger_waters.png
      #  overlay_filter: 0.55 # same as adding an opacity of 0.5 to a black background
  -
    scope:
      path: "_posts"
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
      published: true
      excerpt_separator: <!--more-->
      header: false
      #toc: false
      #header:
        #image: /assets/images/sf.png
      #  overlay_image: /assets/images/sf.png
      #  overlay_filter: 0.55 # same as adding an opacity of 0.5 to a black background

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
