# See https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

locale: "en-US"
title: "Patrice Ferrot"
title_separator: "|"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.io.pferrot" # the base hostname & protocol for your site, e.g. http://example.com
repository: "pferrot/pferrot.github.io"


author:
  name   : "Patrice Ferrot"
  avatar : "/assets/images/pferrot.png"
  bio    : "software engineer.<br>&nbsp;&nbsp;&nbsp;&nbsp;cloud.<br>&nbsp;&nbsp;&nbsp;&nbsp;distributed systems.<br>&nbsp;&nbsp;&nbsp;&nbsp;devops.<br>(rock) music lover.<br>squash player.<br>federer fan.<br>snowboarder."
  #email  : "top secret :-)"
  #uri    : "https://github.io.pferrot"
  home   : # null (default), "absolute or relative url to link to author home"
  github : "pferrot"
  twitter: "patriceferrot"
  linkedin: "patrice-ferrot-599743a"
  lastfm: "stupidillusion"

twitter:
  username: patriceferrot
# Build settings
markdown: kramdown
#theme: minima
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
#minimal_mistakes_skin: "dirt" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
